using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BamsongiController : MonoBehaviour 
{

    public int forwardForce = 2000;
    public int upForce = 200;
    void Start() 
    {
        Application.targetFrameRate = 60;
        Shoot(new Vector3(0, upForce, 2000));
    }


    void Shoot(Vector3 dir) 
    {
        GetComponent<Rigidbody>().AddForce(dir);
    }
    private void OnCollisionEnter(Collision collision)
    {
        GetComponent<Rigidbody>().isKinematic = true;
        GetComponent<ParticleSystem>().Play();
        GetComponentsInChildren<MeshRenderer>()[0].enabled = false;
        Destroy(gameObject, 1);
    }
}
